### Numpy:
            - Numpy stands for numerical python.
            - It is mainly used for N-dimensional arrays.
            - First we need to import numpy package.
- How to create numpy array:
    - using list,tuple,dictionary,range and arange function.
- syntax of numpy array:
    - variable_name = numpy.array(list/dict/tuple)

In [1]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [4]:
print(len(dir(np)))

608


In [5]:
# To know the current version of numpy..
np.__version__

'1.20.1'

In [7]:
# To create 1-d numpy array using list?
# By default numpy will take the floating values...
n1 = np.array([10,20,34,67])
print(n1)
print(type(n1))

[10 20 34 67]
<class 'numpy.ndarray'>


In [8]:
# To create the 2-d numpy array using list?
n2 = np.array([[1,2,3],[5,6,7]])
print(n2)
print(type(n2))

[[1 2 3]
 [5 6 7]]
<class 'numpy.ndarray'>


In [15]:
# Attributes of numpy array?
print(n2)
print(n2.shape)# To know the row size and column size
print(n2.ndim) # To know the dimensions
print(n2.dtype) # To know the data type
print(n2.size) # To know the number of elements
print(n2.itemsize)# To know the each element size in bytes.

[[1 2 3]
 [5 6 7]]
(2, 3)
2
int32
6
4


In [17]:
# To create the numpy array using tuple..
t2 = np.array((10,20,30))
print(t2)
print(type(t2))

[10 20 30]
<class 'numpy.ndarray'>


In [19]:
# To create the numpy array using dicitonary?
d = np.array({'name':'nethra','rollno':510})
print(d)
print(type(d))

{'name': 'nethra', 'rollno': 510}
<class 'numpy.ndarray'>


In [20]:
# Using range function we can create the numpy array...
n3 = np.array(range(1,10))
print(n3)

[1 2 3 4 5 6 7 8 9]


In [23]:
# using arange function we can create the numpy array..
n4 = np.arange(20,45)
print(n4)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44]


In [24]:
n5 = np.array(range(1.3,23.4))
print(n5)

TypeError: 'float' object cannot be interpreted as an integer

In [25]:
k = np.arange(1.4,23.6)
print(k)

[ 1.4  2.4  3.4  4.4  5.4  6.4  7.4  8.4  9.4 10.4 11.4 12.4 13.4 14.4
 15.4 16.4 17.4 18.4 19.4 20.4 21.4 22.4 23.4]


In [26]:
np.array(range(10,100,4))

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74,
       78, 82, 86, 90, 94, 98])

In [28]:
# linspace
# by default the linspace will return 50 equal parts..
n = np.linspace(1,10)
print(n)
print(n.ndim)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
1


In [30]:
m = np.linspace(10,30,7)
print(m)

[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667
 30.        ]


In [33]:
# To change datatype .. using dtype attribute?
n1 = np.array([10,20,30],dtype=float)
print(n1)

[10. 20. 30.]


### Array Initialization:

In [38]:
# Using Zeros method to create 1-d array
a1 = np.zeros(4)
print(a1)
print(a1.ndim)

[0. 0. 0. 0.]
1


In [40]:
# 2-d array using zeros method...
b1 = np.zeros((2,3),dtype=int)
print(b1)
print(b1.ndim)

[[0 0 0]
 [0 0 0]]
2


In [41]:
# Using ones method to create 1-d array?
c = np.ones(5)
print(c)

[1. 1. 1. 1. 1.]


In [42]:
# 2-d array 
d = np.ones((2,2),dtype=int)
print(d)

[[1 1]
 [1 1]]


In [44]:
# To print the identity matrix?
p = np.eye((3),dtype=int)
print(p)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [45]:
# To print the diagonal values...
s = np.diag([2,3,4])
print(s)

[[2 0 0]
 [0 3 0]
 [0 0 4]]


In [46]:
# To print the specific value...
k = np.full(4,7) # 1d array
print(k)

[7 7 7 7]


In [47]:
m = np.full((2,3),6) # 2d array
print(m)

[[6 6 6]
 [6 6 6]]


### Arithmetic operations:

In [55]:
# To perform the arithmetic operations.
n1 = np.array([[1,2],[3,4]])
print(n1)
n2 = np.array([[1,1],[2,2]])
print(n2)
print('-------------')
print("Addition is: \n",n1+n2)
print('Element wise product: \n',n1*n2) # element wise product
print('matrix multiplication is: \n',n1.dot(n2))

[[1 2]
 [3 4]]
[[1 1]
 [2 2]]
-------------
Addition is: 
 [[2 3]
 [5 6]]
Element wise product: 
 [[1 2]
 [6 8]]
matrix multiplication is: 
 [[ 5  5]
 [11 11]]


### Random():
            - It is one of the submodule in Numpy.
            - It is used to generate the random elements in between range.

In [58]:
# Sub module in numpy
rn = np.random
print(dir(rn))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uni

#### random():
- 1. np.random.randint()
        - To generate single random integer in the given range.
- 2. np.random.rand()
        - It creates the random array of digits from 0.
- 3. np.random.randn()
        - It creates the -ve random integers from i.e -1.
- 4. np.random.random()
        - It creates the random array of size mentioned from 0.

In [61]:
# To generate the single random integer...
t = np.random.randint(20,34)
print(t)

22


In [62]:
# To generate the number of random inetegers..
r = np.random.randint(50,100,10) # 1d array
print(r)

[58 92 50 76 81 86 69 78 68 59]


In [64]:
# To generate the 2d array using random function..
n1 = np.random.randint(10,50,(2,2))
print(n1)

[[31 32]
 [40 22]]


In [67]:
np.random.rand(2,3)

array([[0.2600879 , 0.58582917, 0.84052032],
       [0.7870464 , 0.99832168, 0.03059561]])

In [69]:
np.random.randn(4,2)

array([[ 0.48930717, -1.10210253],
       [ 1.7397239 , -0.4875943 ],
       [-0.64862105,  1.26846882],
       [-0.05599243, -0.30627185]])

In [71]:
np.random.random((2,3))

array([[0.56977064, 0.30830474, 0.47480835],
       [0.19698433, 0.48419285, 0.87461286]])

### Indexing:

In [72]:
n = np.random.randint(10,100,(6,6))
print(n)

[[24 18 25 96 17 74]
 [12 14 81 32 65 12]
 [41 29 87 34 66 27]
 [84 43 12 20 99 43]
 [40 42 48 81 93 90]
 [87 71 41 45 55 93]]


In [75]:
print(n[0])# To get first row
print(n[-1])# To get last row
print(n[::]) # To print the entire matrix

[24 18 25 96 17 74]
[87 71 41 45 55 93]
[[24 18 25 96 17 74]
 [12 14 81 32 65 12]
 [41 29 87 34 66 27]
 [84 43 12 20 99 43]
 [40 42 48 81 93 90]
 [87 71 41 45 55 93]]


In [78]:
# Boolean indexing and fancy indexing
# boolean indexing-> It will return true or false.
# fancy indexing -> It will return the value.
print(n)

[[24 18 25 96 17 74]
 [12 14 81 32 65 12]
 [41 29 87 34 66 27]
 [84 43 12 20 99 43]
 [40 42 48 81 93 90]
 [87 71 41 45 55 93]]


In [79]:
# boolean indexing...
print(n<30)

[[ True  True  True False  True False]
 [ True  True False False False  True]
 [False  True False False False  True]
 [False False  True  True False False]
 [False False False False False False]
 [False False False False False False]]


In [80]:
# fancy indexing..
print(n[n<30])

[24 18 25 17 12 14 12 29 27 12 20]


### filtering or slicing:
            - slicing :[start:stop:step]
            - start value: 0 -> optional
            - stop value: size-1
            - step value: 1 -> optional

In [83]:
print(n)
print(n.shape)
print(n[1:5]) # To remove the first and last rows

[[24 18 25 96 17 74]
 [12 14 81 32 65 12]
 [41 29 87 34 66 27]
 [84 43 12 20 99 43]
 [40 42 48 81 93 90]
 [87 71 41 45 55 93]]
(6, 6)
[[12 14 81 32 65 12]
 [41 29 87 34 66 27]
 [84 43 12 20 99 43]
 [40 42 48 81 93 90]]


In [86]:
# TO print the alternative rows..
print(n[::2])
print('--------------------')
print(n)

[[24 18 25 96 17 74]
 [41 29 87 34 66 27]
 [40 42 48 81 93 90]]
--------------------
[[24 18 25 96 17 74]
 [12 14 81 32 65 12]
 [41 29 87 34 66 27]
 [84 43 12 20 99 43]
 [40 42 48 81 93 90]
 [87 71 41 45 55 93]]


In [87]:
# To print the specific value based on row and column
print(n[1][3]) # 1 row and 3rd column value

32


### Reshape and Resize:
        - Reshape:
                To convert the 1-d array to n-d array.
        - resize:
                To change the row size and column size.(increase or decrease)

In [90]:
# TO convert the 1d array to nd array..
n1 = np.arange(16).reshape(4,4)
print(n1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [91]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [92]:
np.arange(4).reshape(1,4)

array([[0, 1, 2, 3]])

In [93]:
np.arange(20).reshape(5,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [94]:
np.arange(24).reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [98]:
# resize of numpy array
# syntax: np.resize(arrayname,(rowsize,columnsize))
n = np.array([[1,2],[4,5]])
print(n)
print('resize array')
print(np.resize(n,(3,3)))

[[1 2]
 [4 5]]
resize array
[[1 2 4]
 [5 1 2]
 [4 5 1]]
